<a href="https://colab.research.google.com/github/praneshnikhar/Deep-Learning-models/blob/main/word_embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sent = ['the glass of milk',
        'the glass of juice',
        'the cup of tea',
        'i am a good developer',
        'understand the meaning of words',
        ]

In [3]:
sent


['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good developer',
 'understand the meaning of words']

In [5]:
voc_size = 10000
#vocabb size
onehot_repr = [one_hot(words,voc_size) for words in sent]
print(onehot_repr)

[[1066, 3835, 304, 5992], [1066, 3835, 304, 5766], [1066, 9363, 304, 2536], [5241, 7609, 1484, 8467, 6975], [1601, 1066, 8687, 304, 2080]]


In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding = 'pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0    0 1066 3835  304 5992]
 [   0    0    0    0 1066 3835  304 5766]
 [   0    0    0    0 1066 9363  304 2536]
 [   0    0    0 5241 7609 1484 8467 6975]
 [   0    0    0 1601 1066 8687  304 2080]]


In [8]:
dim = 15


In [9]:
model = Sequential()
model.add(Embedding(voc_size, 10, input_length = sent_length))
model.compile('adam', 'mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [10]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [11]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 368ms/step
[[[ 0.02266962  0.00883977  0.02974118 -0.04099556  0.00147705
   -0.03288656 -0.01361935 -0.01236081  0.01248398  0.02289652]
  [ 0.02266962  0.00883977  0.02974118 -0.04099556  0.00147705
   -0.03288656 -0.01361935 -0.01236081  0.01248398  0.02289652]
  [ 0.02266962  0.00883977  0.02974118 -0.04099556  0.00147705
   -0.03288656 -0.01361935 -0.01236081  0.01248398  0.02289652]
  [ 0.02266962  0.00883977  0.02974118 -0.04099556  0.00147705
   -0.03288656 -0.01361935 -0.01236081  0.01248398  0.02289652]
  [ 0.02804274  0.03290929  0.02878984  0.04384274  0.03207522
   -0.00179659  0.00988976 -0.02954371 -0.04042207  0.0075425 ]
  [ 0.00532074 -0.00167146 -0.0151582   0.0376409   0.03235349
   -0.0287382   0.01461386 -0.04848778  0.00728207  0.01710642]
  [ 0.0259863   0.00553981 -0.01039395 -0.02369862 -0.00263585
   -0.0203791  -0.01959136  0.03082642  0.03782381  0.03994009]
  [ 0.02258033 -0.02094901  0.00541494 -0.00556661 -0.03827511
   -0.014

In [12]:
embedded_docs

array([[   0,    0,    0,    0, 1066, 3835,  304, 5992],
       [   0,    0,    0,    0, 1066, 3835,  304, 5766],
       [   0,    0,    0,    0, 1066, 9363,  304, 2536],
       [   0,    0,    0, 5241, 7609, 1484, 8467, 6975],
       [   0,    0,    0, 1601, 1066, 8687,  304, 2080]], dtype=int32)

In [13]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step
[[ 0.02266962  0.00883977  0.02974118 -0.04099556  0.00147705 -0.03288656
  -0.01361935 -0.01236081  0.01248398  0.02289652]
 [ 0.02266962  0.00883977  0.02974118 -0.04099556  0.00147705 -0.03288656
  -0.01361935 -0.01236081  0.01248398  0.02289652]
 [ 0.02266962  0.00883977  0.02974118 -0.04099556  0.00147705 -0.03288656
  -0.01361935 -0.01236081  0.01248398  0.02289652]
 [ 0.02266962  0.00883977  0.02974118 -0.04099556  0.00147705 -0.03288656
  -0.01361935 -0.01236081  0.01248398  0.02289652]
 [ 0.02804274  0.03290929  0.02878984  0.04384274  0.03207522 -0.00179659
   0.00988976 -0.02954371 -0.04042207  0.0075425 ]
 [ 0.00532074 -0.00167146 -0.0151582   0.0376409   0.03235349 -0.0287382
   0.01461386 -0.04848778  0.00728207  0.01710642]
 [ 0.0259863   0.00553981 -0.01039395 -0.02369862 -0.00263585 -0.0203791
  -0.01959136  0.03082642  0.03782381  0.03994009]
 [ 0.02258033 -0.02094901  0.00541494 -0.00556661 -0.03827511 -0.01489428
  -0.00551786 -